services:
  homeapi-app:
    image: homeapi-raspberrypi
    container_name: homeapi-app
    build:
      context: .
      dockerfile: required/docker/Dockerfile
    volumes:
      - ".:/go/src/homeapi"
    ports:
      - "1323:1323"
      - "5050:5050" #delve用のポート
    privileged: true # Delveで必要なので付与します。セキュリティ面から本番環境では使うべきではありません。
    command: >
      bash -c "chmod +x required/docker/startup.sh &&
      required/docker/startup.sh"
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
    environment:
      GO_ENV: develop
    env_file:
      - develop.env
    tty: true
    depends_on:
      - mysql
  mysql:
    image: mysql:8
    container_name: homeapi-mysql
    volumes:
      - ./required/db-data/mysql_data:/var/lib/mysql
      - ./required/docker/mysql:/docker-entrypoint-initdb.d
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    env_file:
      - develop.env
    environment:
      - MYSQL_ROOT_PASSWORD=qMc-4o37Y # 各自設定してください
      - MYSQL_DATABASE=homeapi
      - MYSQL_USER=homeapi
      - MYSQL_PASSWORD=qMc-4o37Y # 各自設定してください
    ports:
      - "13306:3306"
    tty: true
  homeapi-redis:
    image: redis:latest
    container_name: homeapi-redis
    ports:
      - "26379:6379"
    volumes:
      - ./required/db-data/redis/misc/data:/data
      - ./required/docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
