
development:
    dialect: mysql
    dir: migrations
    datasource: homeapi:qMc-4o37Y@tcp(homeapi-mysql)/homeapi?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=true

production:
    dialect: mysql
    dir: migrations
    datasource: homeapi:Diamond_0129@tcp(153.122.115.85)/homeapi?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=true
